# Generated by Django 3.2.5 on 2021-07-19 00:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegrafModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=6)),
                ('created', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('content', models.TextField()),
            ],
        ),
    ]
