# Generated by Django 3.2.5 on 2021-07-24 03:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrafmodel',
            options={'ordering': ['-created', 'uri'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='telegrafmodel',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='telegrafmodel',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='telegrafmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='telegrafmodel',
            name='uri',
            field=models.CharField(max_length=6, verbose_name='Ссылка'),
        ),
    ]
