# Generated by Django 3.2.5 on 2021-08-01 01:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210724_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrafmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='telegrafmodel',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='telegrafmodel',
            name='uri',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Ссылка'),
        ),
    ]
